name = "rails49"
compatibility_date = "2024-04-01"
pages_build_output_dir = "ui/dist"

[[d1_databases]]
binding = "DB"
database_name = "rails49-db"
database_id = "41cc44eb-ccb9-49f4-968f-70a1ddff133e"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "rails49-assets"

[vars]
ADMIN_EMAIL = "admin@rails49.org"
NODE_ENV = "production"
